### ISSUE TITLE
how to use onClick

### ISSUE THREAD

**Issue by EnricoSchiller** [saravanajd/autocomplete#1]
Hello, is there an example which shows how to use the onClick option?
Would like to get the data-value of the selected item.
Currently using this little function but the onClick would be handier :)

`        $('.search').on('click','.autocomplete-list',function(){
            window.location.href = '/'+$(this).find('li.selected').attr('data-value');
        })`

**Comment by saravanajd** [comment]
Now i am added the onClick event.

Please click [here](https://saravanajd.github.io/autocomplete/index.html) to see the example.
